url: http://easy-cms.nikola.loc/public/
database:
  dbname: easycms
  driver: pdo_mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
debug: true
secret: 2z7e7we2e77mjfkiqowc=+
app: Dibz
captcha:
  url: https://www.google.com/recaptcha/api/siteverify
  siteKey: 6LfjPg4TAAAAAEuS9_2NIQAp-knyCIbnoLBSAq2L
  secret: 6LfjPg4TAAAAACM-y8OQuqmgwy6Xhra-hZDcHOgp
